### ISSUE TITLE
header tabs

### ISSUE THREAD

**Issue by ghost** [dbitouze/french-tse#31]
Did you notice that in the header the main categories' tabs (Questions / Mots-clés / Utilisateurs / Distinctions / Sans réponse) are one line over the "Poser une question" tab?

My guess : it is because we changed "badge" into "distinctions"; as a 12 characters word need more space than a 5 one (even with 3 "i" in it), the space needed for the five first tabs "pushed" the last one under the others.

This needs CSS work.

**Comment by ghost** [comment]
The tab field has the "nav" id : div id : nav

In "/osqa/m/default/media/style/style.css" I find:

#nav {
    float: right;
    margin: 35px 0px 0px 0px;
    width: 750px;
}

My guess: adding some px to "width". Why not starting with a 800px try ?

**Comment by dbitouze** [comment]
Done.
