### ISSUE TITLE
Email de notification

### ISSUE THREAD

**Issue by maieul** [dbitouze/french-tse#43]
Pour mes précédentes questions, je recevais des emails de notifications des réponses.

Pas pour http://texnique.fr/osqa/questions/1346/

**Comment by dbitouze** [comment]
Please fill the issues in English. 

OSQA notifications' system indeed seems to be buggy (cf. e.g. #37).

**Comment by maieul** [comment]
oh, ok. as it was on a french project I thought I could write in French, as I thought the problem was specific to this website, and not to the software

**Comment by dbitouze** [comment]
Stefan Kottwitz, who doesn't read French is involved a lot in the technical aspect of [texnique.fr](texnique.fr), hence the preferred  language for issues is English (see README of this repository).

I guess the problem is not specific to our website, but more generally to the underlying software.
