### ISSUE TITLE
FAQ: connection

### ISSUE THREAD

**Issue by ghost** [dbitouze/french-tse#9]
In the page http://texnique.fr/osqa/faq/ I read :

...dois-je créer un nouveau compte ?
Non, ce n'est pas nécessaire. Vous pouvez vous connecter grâce à un service qui prend en charge OpenID, par exemple, Google, Yahoo, AOL, etc. 

Shouldn't it be:

...dois-je créer un nouveau compte ?
Vous pouvez le faire, mais ce n'est pas indispensable : il vous est également possible de vous connecter grâce à un service qui prend en charge OpenID, par exemple, Google, Yahoo, AOL, etc.

**Comment by dbitouze** [comment]
True: it was unclear and I specified it a bit more in commits a496bba1b2e20a830ca7b3de2f72b9dc52abc628 and 2bdba9cc7ba961ec1c20855e2137e333c938a8a5. It is OK for you?
